language: php

php:
  - 8.0
  - nightly

matrix:
  allow_failures:
    - php: 8.0

# services:

#before_install:

#install:
  swoole.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

before_script:
  - composer update --ignore-platform-reqs --prefer-stable

script:
  - php vendor/bin/phpunit --configuration phpunit.travis.xml
